name: GetTor

on:
  workflow_dispatch: 
  schedule:
    - cron: "0 * * * *"
  
  
permissions:
  contents: write

jobs:

  gettor:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Download release data
      run: |
        curl https://aus1.torproject.org/torbrowser/update_3/release/downloads.json -o downloads.json
        curl https://aus1.torproject.org/torbrowser/update_3/release/download-android-aarch64.json -o download-android-aarch64.json
        curl https://aus1.torproject.org/torbrowser/update_3/release/download-android-armv7.json -o download-android-armv7.json
        curl https://aus1.torproject.org/torbrowser/update_3/release/download-android-x86.json -o download-android-x86.json
        curl https://aus1.torproject.org/torbrowser/update_3/release/download-android-x86_64.json -o download-android-x86_64.json
    - name: Extract download URLs
      run: |
        jq -r '.. | .binary? // empty' downloads.json >> url.txt
        jq -r '.. | .binary? // empty' download-android-aarch64.json >> url.txt
        jq -r '.. | .binary? // empty' download-android-armv7.json >> url.txt
        jq -r '.. | .binary? // empty' download-android-x86.json >> url.txt
        jq -r '.. | .binary? // empty' download-android-x86_64.json >> url.txt
        jq -r '.. | .sig? // empty' downloads.json >> url.txt
        jq -r '.. | .sig? // empty' download-android-aarch64.json >> url.txt
        jq -r '.. | .sig? // empty' download-android-armv7.json >> url.txt
        jq -r '.. | .sig? // empty' download-android-x86.json >> url.txt
        jq -r '.. | .sig? // empty' download-android-x86_64.json >> url.txt
    - name: Extract Tor version and export to environment
      run: |
        version=$(jq -r '.version' downloads.json)
        echo "TOR_VERSION=$version" >> $GITHUB_ENV
    - name: Fetch tor
      run: |
        wget -qi $GITHUB_WORKSPACE/url.txt
    - name: Push to release
      uses: softprops/action-gh-release@v2
      with:
          tag_name: ${{ env.TOR_VERSION }}
          name: ${{ env.TOR_VERSION }}
          files: |
            tor-*.apk
            tor-*.exe
            tor-*.dmg
            tor-*.tar.xz
            tor-*.asc
          preserve_order: true
          make_latest: true
env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
